# Default credentials for login:
# User: admin@example.com
# Password: changeme

services:
    nginx-proxy-manager:
        container_name: nginx-proxy-manager
        restart: always
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        image: jc21/nginx-proxy-manager
        network_mode: host
