# default username: admin
# default password: admin

services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/kanboard_data:/var/www/app/data
      - ./data/kanboard_plugins:/var/www/app/plugins
      - ./data/kanboard_ssl:/etc/nginx/ssl