services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: webtop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - KEYBOARD=de-ch-qwertz
    # volumes:
    #   - ./config:/config 
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped
