services:
    uptime-kuma:
        restart: always
        ports:
            - 3001:3001
        volumes:
            - ./uptimeKumaData:/app/data # This is where the data of the app is stored
        container_name: uptime-kuma
        image: louislam/uptime-kuma