# APP_BASE_URL: This is the base public URL where the service will be running.
#	- If Joplin Server needs to be accessible over the internet, configure APP_BASE_URL as follows: https://example.com/joplin. 
#	- If Joplin Server does not need to be accessible over the internet, set the the APP_BASE_URL to your server's hostname. 
#     For Example: http://[hostname]:22300. The base URL can include the port.
# APP_PORT: The local port on which the Docker container will listen. 
#	- This would typically be mapped to port to 443 (TLS) with a reverse proxy.
#	- If Joplin Server does not need to be accessible over the internet, the port can be mapped to 22300.
# Login
#	- Default Admin-Mail: admin@localhost
#	- Default Admin-Password: admin

version: '3'

services:
  joplin-db:
    image: postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=joplin

  joplin-app:
    image: joplin/server:latest
    depends_on:
      - joplin-db
    ports:
      - "22300:22300"
    restart: unless-stopped
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=http://127.0.0.1:22300
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=dbuser
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=joplin-db
      - MAX_TIME_DRIFT=0
    volumes:
      - ./data/joplin:/root/.config/joplin-server
